-- Veridian Service Desk's initial schema. IDs are UUIDs generated by Node, so no
-- PostgreSQL extension is required. The migration runner records this file only
-- after this whole script has committed successfully.
CREATE TABLE IF NOT EXISTS schema_migrations (
  version text PRIMARY KEY,
  applied_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS users (
  id uuid PRIMARY KEY,
  email text NOT NULL UNIQUE CHECK (email = lower(email)),
  display_name text NOT NULL,
  password_hash text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS workspaces (
  id uuid PRIMARY KEY,
  owner_user_id uuid NOT NULL UNIQUE REFERENCES users(id),
  name text NOT NULL DEFAULT 'Assessment sandbox',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sessions (
  token_hash char(64) PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users(id),
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS sessions_user_id_idx ON sessions(user_id);
CREATE INDEX IF NOT EXISTS sessions_expiry_idx ON sessions(expires_at);

CREATE TABLE IF NOT EXISTS policies (
  id text PRIMARY KEY,
  title text NOT NULL,
  body text NOT NULL,
  source_file text NOT NULL,
  source_page integer NOT NULL CHECK (source_page > 0),
  source_section text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  search_vector tsvector GENERATED ALWAYS AS (
    to_tsvector('english', coalesce(title, '') || ' ' || body)
  ) STORED
);
CREATE INDEX IF NOT EXISTS policies_search_idx ON policies USING gin(search_vector);

CREATE TABLE IF NOT EXISTS cases (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL REFERENCES workspaces(id),
  source_id text NOT NULL,
  source_kind text NOT NULL CHECK (source_kind IN ('request', 'ticket', 'custom')),
  source_snapshot jsonb NOT NULL,
  source_status text,
  source_date date,
  employee_name text,
  employee_email text,
  original_text text NOT NULL,
  work_state text NOT NULL,
  active boolean NOT NULL,
  facts jsonb NOT NULL DEFAULT '{}'::jsonb,
  fact_evidence jsonb NOT NULL DEFAULT '[]'::jsonb,
  last_decision jsonb,
  version integer NOT NULL DEFAULT 0 CHECK (version >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (workspace_id, id),
  UNIQUE (workspace_id, source_id)
);
CREATE INDEX IF NOT EXISTS cases_workspace_state_idx ON cases(workspace_id, work_state);
CREATE INDEX IF NOT EXISTS cases_workspace_updated_idx ON cases(workspace_id, updated_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS runs (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL,
  case_id uuid NOT NULL,
  idempotency_key text NOT NULL,
  input_hash char(64) NOT NULL,
  status text NOT NULL CHECK (status IN ('RUNNING', 'COMPLETED', 'FAILED', 'INTERRUPTED', 'CONFLICTED')),
  agent_mode text CHECK (agent_mode IN ('gemini', 'offline', 'offline-fallback')),
  case_version integer NOT NULL,
  result jsonb,
  safe_error_code text,
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  FOREIGN KEY (workspace_id, case_id) REFERENCES cases(workspace_id, id),
  UNIQUE (workspace_id, id),
  UNIQUE (workspace_id, idempotency_key)
);
CREATE UNIQUE INDEX IF NOT EXISTS one_running_run_per_case ON runs(workspace_id, case_id) WHERE status = 'RUNNING';
CREATE INDEX IF NOT EXISTS runs_workspace_started_idx ON runs(workspace_id, started_at DESC);

CREATE TABLE IF NOT EXISTS messages (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL,
  case_id uuid NOT NULL,
  run_id uuid,
  role text NOT NULL CHECK (role IN ('user', 'assistant', 'source')),
  content text NOT NULL CHECK (length(content) <= 12000),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (workspace_id, case_id) REFERENCES cases(workspace_id, id),
  FOREIGN KEY (workspace_id, run_id) REFERENCES runs(workspace_id, id),
  UNIQUE (run_id, role)
);
CREATE INDEX IF NOT EXISTS messages_case_idx ON messages(workspace_id, case_id, created_at, id);

CREATE TABLE IF NOT EXISTS service_tickets (
  id uuid PRIMARY KEY,
  workspace_id uuid NOT NULL,
  case_id uuid NOT NULL,
  display_id text NOT NULL,
  route text,
  state text NOT NULL,
  original_status text,
  summary text NOT NULL,
  reason_code text,
  policy_source_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  history_source_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (workspace_id, case_id) REFERENCES cases(workspace_id, id),
  UNIQUE (workspace_id, case_id),
  UNIQUE (workspace_id, display_id)
);
CREATE INDEX IF NOT EXISTS service_tickets_workspace_state_idx ON service_tickets(workspace_id, state);

CREATE TABLE IF NOT EXISTS audit_events (
  sequence_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id uuid NOT NULL UNIQUE,
  workspace_id uuid NOT NULL REFERENCES workspaces(id),
  case_id uuid,
  run_id uuid,
  actor_user_id uuid REFERENCES users(id),
  event_type text NOT NULL,
  node_name text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (workspace_id, case_id) REFERENCES cases(workspace_id, id),
  FOREIGN KEY (workspace_id, run_id) REFERENCES runs(workspace_id, id)
);
CREATE INDEX IF NOT EXISTS audit_workspace_sequence_idx ON audit_events(workspace_id, sequence_id);

CREATE OR REPLACE FUNCTION deny_audit_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'Audit records are append-only';
END;
$$;
DROP TRIGGER IF EXISTS audit_no_update_delete ON audit_events;
CREATE TRIGGER audit_no_update_delete
  BEFORE UPDATE OR DELETE ON audit_events
  FOR EACH ROW EXECUTE FUNCTION deny_audit_mutation();
