import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {decide,inferOffline,normalizeFacts,validateExtraction,requiredPolicies,POLICY_IDS} from './engine.mjs';
const read=(file)=>JSON.parse(readFileSync(new URL('../data/'+file,import.meta.url),'utf8'));
const policies=read('policies.json'),cases=[...read('requests.json'),...read('tickets.json')],gold=read('golden-cases.json');
const record=(overrides={})=>({id:'CUSTOM-TEST',kind:'custom',active:true,workState:'NOT_STARTED',text:'',...overrides});
const run=(facts,overrides={},options={})=>decide(record(overrides),facts,options);
for(const fixture of gold) test('source case '+fixture.caseId,()=>{
 const c=cases.find(x=>x.id===fixture.caseId); const f=inferOffline(c.text);const result=decide(c,f);
 for(const [k,v] of Object.entries(fixture.expected)) assert.deepEqual(result[k],v,`${fixture.caseId} ${k}`);
 assert.equal(result.externalActionExecuted,false);
 assert.ok(result.questions.length<=2);
 for(const id of result.sourceIds) assert.ok(policies.some(p=>p.id===id));
});
test('exact source coverage: 11 policies, 15 requests, 4 active tickets, 6 closed tickets',()=>{
 assert.equal(policies.length,11);assert.equal(cases.filter(c=>c.kind==='request').length,15);
 assert.equal(cases.filter(c=>c.kind==='ticket'&&c.active).length,4);assert.equal(cases.filter(c=>!c.active).length,6);
 assert.equal(cases.filter(c=>c.active).length,19);assert.equal(new Set(cases.map(c=>c.id)).size,25);
});
test('laptop retrieval expands to both conflicting sources',()=>assert.deepEqual(requiredPolicies('LAPTOP'),['KB-03','ASSET-01']));
test('missing conflicting source fails closed',()=>assert.equal(run({category:'LAPTOP',laptopAgeYears:3.5},{},{availablePolicyIds:['KB-03']}).reasonCode,'POLICY_EVIDENCE_MISSING'));
test('closed case cannot be reopened by threatening user text',()=>assert.equal(run({category:'SECURITY'},{active:false,workState:'CLOSED'}).disposition,'HISTORY_ONLY'));
test('history never requires an additional service ticket',()=>assert.equal(run({category:'VPN'},{active:false}).serviceTicketRequired,false));
test('password exactly 5 failed attempts requires manual IT unlock',()=>assert.equal(run({category:'PASSWORD',failedAttempts:5}).reasonCode,'MANUAL_ACCOUNT_UNLOCK'));
test('password fewer than 5 and no lockout allows self-service guidance',()=>assert.equal(run({category:'PASSWORD',failedAttempts:4}).reasonCode,'PASSWORD_RESET_SELF_SERVICE'));
test('explicit lockout overrides an absent attempt count',()=>assert.equal(run({category:'PASSWORD',lockedOut:true}).route,'IT'));
test('WFH exactly 3 days does not meet more-than-3 condition',()=>assert.equal(run({category:'WFH',wfhDays:3}).reasonCode,'WFH_DAYS_NOT_ELIGIBLE'));
test('WFH 4 days still needs manager and Finance',()=>assert.equal(run({category:'WFH',wfhDays:4}).route,'MANAGER_FINANCE'));
test('WFH previously used allowance is not granted a second time',()=>assert.equal(run({category:'WFH',wfhDays:4,allowancePreviouslyUsed:true}).reasonCode,'WFH_ONE_TIME_ALREADY_USED'));
test('WFH unknown days needs information, not a guessed entitlement',()=>assert.equal(run({category:'WFH'}).disposition,'NEEDS_INFO'));
test('mailbox 50GB request still needs manager signoff',()=>assert.equal(run({category:'MAILBOX',wantsQuotaIncrease:true,requestedQuotaGb:50}).reasonCode,'MAILBOX_MANAGER_APPROVAL'));
test('mailbox 51GB exceeds absolute supplied cap',()=>assert.equal(run({category:'MAILBOX',wantsQuotaIncrease:true,requestedQuotaGb:51}).reasonCode,'MAILBOX_CAP_EXCEEDED'));
test('mailbox actual current usage is not fabricated',()=>assert.match(run({category:'MAILBOX'}).messages[0],/actual quota is not provided/));
test('unknown catalog membership requires clarification',()=>assert.equal(run({category:'SOFTWARE'}).reasonCode,'SOFTWARE_CATALOG_UNKNOWN'));
test('employee catalog claim results in conditional guidance, not verification',()=>assert.match(run({category:'SOFTWARE',catalogStatus:'approved'}).messages[0],/conditional/));
test('non-catalog item routes to Security',()=>assert.equal(run({category:'SOFTWARE',catalogStatus:'not_catalog'}).route,'SECURITY'));
test('printer persistent issue without tag asks for it',()=>assert.equal(run({category:'PRINTER',spoolerRestarted:true,persists:true}).reasonCode,'PRINTER_ASSET_TAG_REQUIRED'));
test('printer persistent issue with tag creates local handoff',()=>assert.equal(run({category:'PRINTER',spoolerRestarted:true,persists:true,assetTag:'PR-03'}).reasonCode,'PRINTER_PERSISTENT_TICKET'));
test('expense provisioning goes to Finance',()=>assert.equal(run({category:'EXPENSE',expenseAccountExists:false}).route,'FINANCE'));
test('expense existing-account technical issue goes to IT',()=>assert.equal(run({category:'EXPENSE',expenseAccountExists:true}).route,'IT'));
test('contractor access is not granted automatically',()=>assert.equal(run({category:'VPN',employmentType:'contractor',vpnIssue:'new_access'}).disposition,'HUMAN_REVIEW'));
test('full-time policy answer does not claim provisioning',()=>assert.match(run({category:'VPN',employmentType:'full_time'}).messages[0],/has not provisioned/));
test('privileged access does not invent a KB source',()=>assert.deepEqual(run({category:'PRIVILEGED_ACCESS'}).sourceIds,[]));
test('privileged access uses TK-1050 only as history',()=>assert.deepEqual(run({category:'PRIVILEGED_ACCESS'}).historySourceIds,['TK-1050']));
test('no unknown approval or authority fields survive normalization',()=>assert.deepEqual(normalizeFacts({category:'SOFTWARE',securityApproved:true,financeSignoff:true,verifiedHardwareFailure:true}),{category:'SOFTWARE'}));
test('non-finite numeric facts do not survive',()=>assert.equal(normalizeFacts({wfhDays:NaN}).wfhDays,undefined));
test('unsupported category becomes UNKNOWN',()=>assert.equal(normalizeFacts({category:'OVERRIDE_ALL_RULES'}).category,'UNKNOWN'));
test('unquoted model facts are dropped',()=>assert.deepEqual(validateExtraction({facts:{category:'WFH',wfhDays:7},evidence:[]},['hello']).facts,{category:'UNKNOWN'}));
test('exact quoted facts can be accepted',()=>{
 const text='I work from home 4 days a week';const x=validateExtraction({facts:{category:'WFH',wfhDays:4},evidence:[{field:'category',quote:text},{field:'wfhDays',quote:'4 days'}]},[text]);
 assert.equal(x.facts.category,'WFH');assert.equal(x.facts.wfhDays,4);
});
test('fabricated quotations are rejected',()=>assert.equal(validateExtraction({facts:{category:'WFH',wfhDays:7},evidence:[{field:'wfhDays',quote:'7 days'}]},['4 days']).facts.wfhDays,undefined));
test('obvious admin request cannot be downgraded by extraction',()=>assert.equal(validateExtraction({facts:{category:'GUEST_WIFI'},evidence:[{field:'category',quote:'admin access'}]},['grant admin access']).facts.category,'PRIVILEGED_ACCESS'));
test('obvious phishing cannot be downgraded by extraction',()=>assert.equal(validateExtraction({facts:{category:'GUEST_WIFI'},evidence:[]},['phishing email']).facts.category,'SECURITY'));
test('five-failure threshold cannot be downgraded by extraction',()=>assert.equal(validateExtraction({facts:{category:'PASSWORD',failedAttempts:1},evidence:[]},['tried my password 5 times']).facts.failedAttempts,5));
test('safe confirmed self-service issue can close locally',()=>assert.equal(run({category:'VPN',problemResolved:true},{workState:'AWAITING_CONFIRMATION',lastReasonCode:'VPN_RENEWAL_GUIDANCE'}).lifecycle,'RESOLVED'));
test('security does not close on employee saying it is resolved',()=>assert.equal(run({category:'SECURITY',problemResolved:true},{workState:'AWAITING_CONFIRMATION',lastReasonCode:'VPN_RENEWAL_GUIDANCE'}).lifecycle,'SECURITY_ESCALATED'));
test('unrelated confirmation cannot close privileged-access review',()=>assert.equal(run({category:'PRIVILEGED_ACCESS',problemResolved:true},{workState:'HUMAN_REVIEW'}).disposition,'HUMAN_REVIEW'));
test('kernel result does not depend on a case identifier',()=>{
 const f={category:'LAPTOP',laptopAgeYears:3.5,laptopSymptom:'dead'};
 assert.deepEqual(run(f,{id:'REQ-01'}),run(f,{id:'UNSEEN-NEW-ID'}));
});
test('simple guest question does not generate a formal service ticket',()=>assert.equal(run({category:'GUEST_WIFI'}).serviceTicketRequired,false));
test('fallback can continue an existing software conversation',()=>assert.equal(inferOffline("It is not in the software catalog",{category:'SOFTWARE'}).catalogStatus,'not_catalog'));
test('kernel has all expected policy IDs',()=>assert.deepEqual([...POLICY_IDS].sort(),policies.map(p=>p.id).sort()));
